apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ai-backend-config
spec:
  healthCheck:
    requestPath: /health
    port: 5001
    type: HTTP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: spring-backend-config
spec:
  healthCheck:
    requestPath: /health
    port: 8080
    type: HTTP

